Created view lists of students and student groups in the admin panel
ita-social-projects/WhatBackend pull request #108
Opened 2020-11-11 12:31 UTC by BohdanBBG

2020-11-11 21:57 UTC, SerjKocherga approved these changes

2020-11-12 14:53 UTC, Vlad1023 approved these changes

2020-11-13 00:47 UTC, SnipeFrost approved these changes

2020-11-13 07:10 UTC, whereismyroot requested changes

2020-11-13 07:10 UTC, whereismyroot commented on CharlieBackend.AdminPanel/Services/Interfaces/IStudentService.cs
> +        public Task<IList<StudentViewModel>> GetAllStudents(string accessToken);
remove public

2020-11-13 07:10 UTC, whereismyroot commented on CharlieBackend.Api/Controllers/AccountsController.cs
> +
remove this

2020-11-13 09:16 UTC, BohdanBBG commented on CharlieBackend.AdminPanel/Utils/ApiUtil.cs
>              return httpResponse.Headers?.FirstOrDefault(x => x.Key == "Authorization").Value?.FirstOrDefault();
Done

2020-11-13 09:29 UTC, whereismyroot approved these changes

2020-11-13 09:29 UTC, merged