Added the ability to edit and delete on the Student and Student groups pages and setted up a page for exceptions.
ita-social-projects/WhatBackend pull request #144
Opened 2020-11-17 09:52 UTC by BohdanBBG

2020-11-17 10:48 UTC, sober607 approved these changes
Good.
@TagHelpers also allows to do not write strings in HTML code. And will allow to implement multilanguage in future

2020-11-17 11:21 UTC, SerjKocherga approved these changes

2020-11-20 10:00 UTC, whereismyroot requested changes
Please, do not create PR's for several tasks and features. Make more small PR's for each task.

2020-11-20 10:00 UTC, whereismyroot commented on CharlieBackend.AdminPanel/Controllers/AccountController.cs
> -    [Route("admin/account")]
leave at least [Route("[controller]")], because otherwise, Login method would be routed to /login

2020-11-20 12:53 UTC, whereismyroot approved these changes

2020-11-20 12:53 UTC, merged