Fix theme controller to return Result T
ita-social-projects/WhatBackend pull request #167
Opened 2020-11-20 13:28 UTC by Vlad1023

Also, commented useless unit test for themes

2020-11-20 14:47 UTC, whereismyroot requested changes

2020-11-20 14:47 UTC, whereismyroot commented on CharlieBackend.Api.UnitTes/Controllers/ThemesControllerTests.cs
> +	//	return ThemesL;
Do not leave commented code

2020-11-20 14:54 UTC, SerjKocherga requested changes

2020-11-20 14:54 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/ThemesController.cs
Remove this empty new line.

2020-11-20 14:54 UTC, SerjKocherga commented on CharlieBackend.Business/Services/ThemeService.cs
Remove this empty new line.

2020-11-20 14:56 UTC, Vlad1023 commented on CharlieBackend.Api.UnitTes/Controllers/ThemesControllerTests.cs
> +	//	return ThemesL;
done

2020-11-20 14:58 UTC, Vlad1023 commented on CharlieBackend.Api/Controllers/ThemesController.cs
done

2020-11-20 14:58 UTC, Vlad1023 commented on CharlieBackend.Business/Services/ThemeService.cs
done

2020-11-20 18:12 UTC, sober607 approved these changes
Ok

2020-11-21 08:59 UTC, whereismyroot approved these changes

2020-11-21 11:57 UTC, SnipeFrost approved these changes

2020-11-22 11:09 UTC, BohdanBBG approved these changes

2020-11-22 23:51 UTC, SerjKocherga approved these changes

2020-11-22 23:53 UTC, merged