Added endpoint for getting student study groups
ita-social-projects/WhatBackend pull request #179
Opened 2020-11-23 17:51 UTC by BohdanBBG

2020-11-23 17:59 UTC, SerjKocherga approved these changes

2020-11-23 17:59 UTC, SerjKocherga commented on CharlieBackend.Api/SwaggerExamples/StudentGroupsController/StudentStudyGroupsResponse.cs
> +
Remove this empty line.

2020-11-23 17:59 UTC, SerjKocherga commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +
Remove this empty line.

2020-11-23 17:59 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/StudentGroupRepository.cs
> +
Remove this empty line.

2020-11-23 17:59 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/StudentRepository.cs
> +
Remove this empty line.

2020-11-23 19:48 UTC, sober607 approved these changes

2020-11-24 05:54 UTC, whereismyroot requested changes
Needs some changes

2020-11-24 05:54 UTC, whereismyroot commented on CharlieBackend.Data/Repositories/Impl/StudentRepository.cs
> +        }
please make this method generic and move it to Repository.cs so it can be used not only for students. Also, please use async version of .Any

2020-11-24 05:54 UTC, whereismyroot commented on CharlieBackend.Api/Controllers/StudentGroupsController.cs
> +        public async Task<ActionResult<IList<StudentStudyGroupsDto>>> GetStudentStudyGroupsByStudentId(long id)
Please move this method to students controller. In your implementation we'd have the following url:
/api/student_groups/student/{id} which is not correct. 
Let's have it here: 
/api/students/{id}/groups

2020-11-24 11:41 UTC, SnipeFrost approved these changes

2020-11-24 11:42 UTC, Vlad1023 approved these changes

2020-11-27 12:27 UTC, x1mx1x approved these changes

2020-11-30 13:28 UTC, merged