Feature/admin panel themes
ita-social-projects/WhatBackend pull request #180
Opened 2020-11-24 01:22 UTC by Vlad1023

Implemented Post, Delete, Update abilities for Themes

2020-11-24 08:50 UTC, sober607 approved these changes

2020-11-24 10:53 UTC, SerjKocherga requested changes

2020-11-24 10:53 UTC, SerjKocherga commented on CharlieBackend.AdminPanel/Controllers/ThemesController.cs
> +            return View("UpdateTheme");
Add a new line before return.

2020-11-24 10:53 UTC, SerjKocherga commented on CharlieBackend.AdminPanel/Services/Interfaces/IThemeService.cs
> +        Task AddThemeAsync(CreateThemeDto themeDto, string accessToken);
Probably it would be better to add new lines between methods.

2020-11-24 16:17 UTC, BohdanBBG approved these changes

2020-11-25 12:57 UTC, SnipeFrost approved these changes

2020-11-26 14:31 UTC, SerjKocherga approved these changes

2020-11-27 12:31 UTC, x1mx1x approved these changes

2020-11-27 16:16 UTC, merged