Feature/add account unit tests
ita-social-projects/WhatBackend pull request #196
Opened 2020-11-29 19:02 UTC by SnipeFrost

1. Added unit test for CreateAccountAsync method .
2. Deleted some not used code .

2020-11-29 19:15 UTC, SerjKocherga requested changes

2020-11-29 19:15 UTC, SerjKocherga commented on CharlieBackend.Api.UnitTes/AccountServiceTests.cs
> +
Remove this empty line.

2020-11-29 19:15 UTC, SerjKocherga commented on CharlieBackend.Api.UnitTes/AccountServiceTests.cs
> +using CharlieBackend.Core.DTO.Account;
Move this above.

2020-11-29 19:16 UTC, SerjKocherga approved these changes

2020-11-30 08:58 UTC, sober607 approved these changes

2020-11-30 11:15 UTC, BohdanBBG approved these changes

2020-11-30 14:17 UTC, x1mx1x approved these changes

2020-11-30 14:20 UTC, whereismyroot approved these changes

2020-11-30 14:21 UTC, merged