Created unit tests for CourseService
ita-social-projects/WhatBackend pull request #210
Opened 2020-12-02 09:22 UTC by BohdanBBG

2020-12-02 10:17 UTC, x1mx1x approved these changes

2020-12-02 11:41 UTC, SerjKocherga requested changes

2020-12-02 11:41 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/CoursesController.cs
> -            if (!ModelState.IsValid) return BadRequest();
Separate task for unit-test and moving a logic from CourseCountroller into CourseService for two different PRs.
It's not good to close 2 different enchantments in one PR.

2020-12-02 11:45 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/CoursesController.cs
> -            if (!ModelState.IsValid) return BadRequest();
For moving a logic from CourseCountroller into CourseService use issue #203

2020-12-02 12:41 UTC, SnipeFrost approved these changes

2020-12-06 11:56 UTC, SerjKocherga approved these changes

2020-12-06 11:57 UTC, Vlad1023 approved these changes

2020-12-06 12:00 UTC, Hlib-mats approved these changes

2020-12-06 12:02 UTC, merged