Added cookie encryption to AP
ita-social-projects/WhatBackend pull request #226
Opened 2020-12-04 08:53 UTC by BohdanBBG

2020-12-04 09:39 UTC, SerjKocherga requested changes

2020-12-04 09:39 UTC, SerjKocherga commented on CharlieBackend.AdminPanel/ApplicationSettings.cs
> +
Remove these empty lines.

2020-12-04 09:57 UTC, BohdanBBG commented on CharlieBackend.AdminPanel/ApplicationSettings.cs
> +
Done

2020-12-04 12:15 UTC, SerjKocherga approved these changes

2020-12-04 14:06 UTC, x1mx1x approved these changes

2020-12-04 14:13 UTC, Vlad1023 approved these changes

2020-12-04 15:42 UTC, SnipeFrost approved these changes

2020-12-06 12:01 UTC, Hlib-mats approved these changes

2020-12-06 12:02 UTC, merged