Feature/add file encoding
ita-social-projects/WhatBackend pull request #230
Opened 2020-12-04 14:29 UTC by x1mx1x

2020-12-04 15:38 UTC, SnipeFrost requested changes

2020-12-04 15:38 UTC, SnipeFrost commented on CharlieBackend.Api/Controllers/ImportController.cs
> +}
add new line in the end of file

2020-12-04 15:38 UTC, SnipeFrost commented on CharlieBackend.Business/Services/GroupImportService.cs
> +                var wb = new XLWorkbook(path);
what is it wb, maybe need change name for more readable

2020-12-04 15:38 UTC, SnipeFrost commented on CharlieBackend.Business/Services/GroupImportService.cs
> +                Type sgType = typeof(StudentGroupFileModel);
Same as above about "wsGroups" and "sgType"

2020-12-04 15:38 UTC, SnipeFrost commented on CharlieBackend.Business/Services/StudentImportService.cs
> +                var wb = new XLWorkbook(await CreateFile(uploadedFile));
Same as above here

2020-12-04 16:09 UTC, SerjKocherga requested changes

2020-12-04 16:09 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/StudentRepository.cs
> +
Remove these empty lines.

2020-12-04 16:09 UTC, SerjKocherga commented on CharlieBackend.Core/FileModels/StudentFileModel.cs
> +using System.Collections.Generic;
Fix using placement.

2020-12-04 16:09 UTC, SerjKocherga commented on CharlieBackend.Business/Services/Interfaces/IStudentGroupService.cs
> +using CharlieBackend.Core.Entities;
Fix using placement for code convention.

2020-12-04 16:09 UTC, BohdanBBG approved these changes

2020-12-04 18:38 UTC, SnipeFrost approved these changes

2020-12-05 16:18 UTC, Hlib-mats approved these changes

2020-12-05 18:37 UTC, SerjKocherga approved these changes

2020-12-06 06:01 UTC, filinskyi approved these changes

2020-12-06 12:02 UTC, merged