Modificaded Update and Delete methods in CourseController
ita-social-projects/WhatBackend pull request #238
Opened 2020-12-06 11:08 UTC by QuestroL

Modificaded Update method CourseController, also i have made Delete method for CourseController and change database script

2020-12-06 11:41 UTC, Hlib-mats requested changes

2020-12-06 11:41 UTC, Hlib-mats commented on CharlieBackend.Api/Controllers/AccountsController.cs
> +﻿    using System;
remove this tab

2020-12-06 11:41 UTC, Hlib-mats commented on CharlieBackend.Business/Services/CourseService.cs
> +            return course;
Add line before return

2020-12-06 11:41 UTC, Hlib-mats commented on CharlieBackend.Business/Services/Interfaces/ICourseService.cs
> +
remove this empty line

2020-12-06 11:41 UTC, Hlib-mats commented on CharlieBackend.Business/Services/CourseService.cs
> +                }
new versin of Course Service return Result<CourseDto>, so there might be some conflicts with null

2020-12-06 13:20 UTC, QuestroL commented on CharlieBackend.Api/Controllers/AccountsController.cs
> +﻿    using System;
Why?

2020-12-06 13:29 UTC, Hlib-mats commented on CharlieBackend.Api/Controllers/AccountsController.cs
> +﻿    using System;
why u add this? i think it useless

2020-12-06 14:03 UTC, SerjKocherga requested changes
Need some changes:

2020-12-06 14:03 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +            return StatusCode(409, "Course already have studet Group!");
Replace "have" to "has".

2020-12-06 14:03 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +
Remove these 2 empty lines above.

2020-12-06 14:03 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +            return Ok(deletecoures);
Add a new line before return.

2020-12-06 14:03 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +
Remove these empty lines till angle brace.

2020-12-06 14:03 UTC, SerjKocherga commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +
Remove these empty lines.

2020-12-06 14:03 UTC, SerjKocherga commented on CharlieBackend.Business/Services/CourseService.cs
> +
Remove this empty line.

2020-12-06 14:03 UTC, SerjKocherga commented on CharlieBackend.Business/Services/Interfaces/ICourseService.cs
> +        public Task<bool> DisableCourceAsync(long id);
Remove access modifiers from the interface.
Also add a new line before method.

2020-12-06 14:03 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/Interfaces/ICourseRepository.cs
> +        Task<bool> IsCourseEmptyAsync(long id);
Add a new line before this method.

2020-12-06 15:14 UTC, filinskyi requested changes

2020-12-06 15:14 UTC, filinskyi commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +
Remove blank lines

2020-12-06 15:14 UTC, filinskyi commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +
Remove blank lines

2020-12-06 15:14 UTC, filinskyi commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +
Remove blank lines

2020-12-07 09:27 UTC, sober607 approved these changes

2020-12-07 12:32 UTC, x1mx1x approved these changes

2020-12-07 12:42 UTC, filinskyi approved these changes

2020-12-08 08:33 UTC, sober607 approved these changes

2020-12-08 19:07 UTC, SnipeFrost approved these changes

2020-12-14 16:13 UTC, whereismyroot requested changes

2020-12-14 16:13 UTC, whereismyroot commented on CharlieBackend.Business/Services/CourseService.cs
> +                if (await _unitOfWork.CourseRepository.IsCourseEmptyAsync(id))
You forgot negation operator

2020-12-14 16:13 UTC, whereismyroot commented on CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
> +            var course = await _applicationContext.Courses.FirstOrDefaultAsync(c => c.Id == id);
add check for IsActive

2020-12-14 16:13 UTC, whereismyroot commented on CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
> +            }
remove if statement since here you'll be dealing only with active courses.
Remark regarding syntax: you can omit comparison with boolean literal and use just course.IsActive

2020-12-14 16:13 UTC, whereismyroot commented on CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
> +        }
Method is called IsCourseEmpty, which means "return true if course has no groups". In your implementation, you're returning true if course has any group

2020-12-14 16:13 UTC, whereismyroot commented on CharlieBackend.Core/Entities/Course.cs
> +        public bool? IsActive { get; set; }
make this non-nullable

2020-12-14 16:13 UTC, whereismyroot commented on CharlieBackend.Business/Services/CourseService.cs
> +            var studentGroup = await _unitOfWork.StudentGroupRepository.GetAllAsync();
You're getting all the groups from db here. Please use _unitOfWork.StudentGroupRepository.GetQueryableNoTracking().AnyAsync

2020-12-16 12:13 UTC, QuestroL commented on CharlieBackend.Business/Services/CourseService.cs
> +                if (await _unitOfWork.CourseRepository.IsCourseEmptyAsync(id))
done

2020-12-16 12:13 UTC, QuestroL commented on CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
> +            var course = await _applicationContext.Courses.FirstOrDefaultAsync(c => c.Id == id);
done

2020-12-18 08:48 UTC, BohdanBBG approved these changes

2020-12-18 10:12 UTC, SerjKocherga approved these changes

2020-12-18 12:47 UTC, Hlib-mats approved these changes

2020-12-21 13:01 UTC, whereismyroot approved these changes

2020-12-21 13:01 UTC, merged