Moving HashPassword logic from AccountService
ita-social-projects/WhatBackend pull request #251
Opened 2020-12-07 18:33 UTC by SerjKocherga

HashPassword methods were moved from AccontService to HashPasswordProvider.

2020-12-07 18:38 UTC, Hlib-mats approved these changes

2020-12-07 18:57 UTC, BohdanBBG approved these changes

2020-12-07 18:57 UTC, whereismyroot requested changes

2020-12-07 18:57 UTC, whereismyroot commented on CharlieBackend.Business/Providers/HashPasswordProvider.cs
> +        public static Int32 Next(Int32 minValue, Int32 maxValue)
You don't need this method as public

2020-12-07 18:57 UTC, whereismyroot commented on CharlieBackend.Business/Providers/HashPasswordProvider.cs
> +    public static class HashPasswordProvider
please rename this to Helpers/PasswordHelper.cs since this class is static

2020-12-07 18:58 UTC, SnipeFrost requested changes

2020-12-07 18:58 UTC, SnipeFrost commented on CharlieBackend.Business/Providers/HashPasswordProvider.cs
> +            StringBuilder sb = new StringBuilder(_saltLen - 1);
rename pls "sb" for more obvious name

2020-12-07 18:58 UTC, SnipeFrost commented on CharlieBackend.Business/Services/AccountService.cs
> +                    user.Password = HashPasswordProvider.HashPassword(changePasswd.NewPassword, user.Salt);
why this property have name "changePasswd" ?

2020-12-07 19:52 UTC, SnipeFrost approved these changes

2020-12-08 08:29 UTC, sober607 approved these changes

2020-12-08 13:49 UTC, x1mx1x approved these changes

2020-12-08 13:49 UTC, x1mx1x commented on CharlieBackend.Business/Helpers/PasswordHelper.cs
> +            //a variable for storing a random character position from the string Str
you should remove comments before merging

2020-12-08 13:49 UTC, x1mx1x commented on CharlieBackend.Business/Helpers/PasswordHelper.cs
> +                Int64 diff = maxValue - minValue;
why do you not use pseudonims?

2020-12-08 15:12 UTC, whereismyroot approved these changes

2020-12-08 15:12 UTC, merged