Add GetActiveSecretories method in SecretariesController
ita-social-projects/WhatBackend pull request #254
Opened 2020-12-08 13:07 UTC by QuestroL

- add GetActiveSecretories method in SecretariesControlle
- add GetActiveSecretariesAsync method in SecretaryService and add it in ISecretaryService
- add GetActiveAsync in SecretaryRepository and add it in ISecretaryRepository

2020-12-08 13:30 UTC, SerjKocherga requested changes

2020-12-08 13:30 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/Interfaces/ISecretaryRepository.cs
> +
Remove this empty line.

2020-12-08 13:30 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/SecretaryRepository.cs
> +
Remove this empty line.

2020-12-08 16:43 UTC, filinskyi approved these changes

2020-12-08 19:06 UTC, SnipeFrost approved these changes

2020-12-11 08:18 UTC, sober607 approved these changes

2020-12-18 08:49 UTC, BohdanBBG approved these changes

2020-12-18 10:11 UTC, SerjKocherga approved these changes

2020-12-18 10:38 UTC, merged