Fix/theme deletion
ita-social-projects/WhatBackend pull request #263
Opened 2020-12-10 16:03 UTC by QuestroL

Fix delete method in ThemeService and add one method in ThemeRepository

2020-12-10 18:02 UTC, SerjKocherga requested changes

2020-12-10 18:02 UTC, SerjKocherga commented on CharlieBackend.Data/Repositories/Impl/Interfaces/IThemeRepository.cs
> +        Task<bool> IsThemeUsed(long themeId);
Please, add new lines between methods declaration.

2020-12-11 08:15 UTC, sober607 approved these changes

2020-12-11 09:12 UTC, SnipeFrost approved these changes

2020-12-15 11:30 UTC, whereismyroot approved these changes

2020-12-15 11:59 UTC, SerjKocherga approved these changes

2020-12-16 19:55 UTC, BohdanBBG approved these changes

2020-12-17 15:04 UTC, filinskyi approved these changes

2020-12-18 10:38 UTC, merged