fixed, course is exist check when creating and updating student group…
ita-social-projects/WhatBackend pull request #270
Opened 2020-12-15 18:33 UTC by filinskyi

… and updated unit test

2020-12-15 18:50 UTC, SnipeFrost approved these changes

2020-12-15 18:58 UTC, SerjKocherga requested changes
Need some changes:

2020-12-15 18:58 UTC, SerjKocherga commented on CharlieBackend.Api.UnitTes/StudentGroupServiceTest.cs
> +            var withNotExistCourseIdStudentGroup = new CreateStudentGroupDto()
Let's name it StudentGroupWithoutCourseId.

2020-12-15 18:58 UTC, SerjKocherga commented on CharlieBackend.Business/Services/StudentGroupService.cs
Please, remove "Console.WriteLine(ex.Message) below.

2020-12-15 18:58 UTC, SerjKocherga commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +                    return Result<StudentGroupDto>.GetError(ErrorCode.ValidationError, "CourseId isn't exist");
"CourseId does not exist".

2020-12-15 21:50 UTC, SerjKocherga approved these changes

2020-12-16 09:33 UTC, sober607 approved these changes

2020-12-16 19:55 UTC, BohdanBBG approved these changes

2020-12-18 12:48 UTC, Hlib-mats approved these changes

2020-12-22 12:28 UTC, whereismyroot approved these changes

2020-12-22 12:28 UTC, merged