Add update homework
ita-social-projects/WhatBackend pull request #290
Opened 2020-12-30 11:01 UTC by sober607

1. Added homework update
2. Changed from CreateHomeworkDto to HomeworkRequestDto to simplyfy request validations
3. Added GetHomeworksOfStudentGroup() action
#273

2021-01-02 10:25 UTC, filinskyi commented on CharlieBackend.Api/Controllers/ThemesController.cs
>  }
add a blank line to the end of the file

2021-01-02 10:41 UTC, filinskyi requested changes
a small fix needed

2021-01-03 13:41 UTC, QuestroL approved these changes

2021-01-03 17:49 UTC, SnipeFrost approved these changes

2021-01-04 13:26 UTC, Hlib-mats approved these changes

2021-01-04 13:26 UTC, Hlib-mats commented on CharlieBackend.Business/Services/HomeworkService.cs
> +            }
I think this is unnecessary
it should return success and empty list

2021-01-09 13:20 UTC, filinskyi approved these changes

2021-01-09 22:25 UTC, merged