Feature/get all lesson for mentor
ita-social-projects/WhatBackend pull request #292
Opened 2021-01-04 08:19 UTC by QuestroL

Add new Endpoint to mentorController (GetAllLessonForMentor)

2021-01-04 16:24 UTC, filinskyi requested changes
Small changes required

2021-01-04 16:24 UTC, filinskyi commented on CharlieBackend.Business/Services/MentorService.cs
> +                return Result<IList<LessonDto>>.GetError(ErrorCode.ValidationError, "Write Mentod Id please");
In error message fix "Mentod" to "Mentor"

2021-01-04 16:24 UTC, filinskyi commented on CharlieBackend.Api/Controllers/MentorsController.cs
> +        /// Returns list of lessons  for mentor
Remove extra space between "lessons" and "for"

2021-01-04 16:24 UTC, filinskyi commented on CharlieBackend.Api/Controllers/MentorsController.cs
> +        /// <response code="200">Successful return of lessons list of given student</response>
Replace "student" to "mentor"

2021-01-04 16:24 UTC, filinskyi commented on CharlieBackend.Business/Services/MentorService.cs
> +                return Result<IList<LessonDto>>.GetError(ErrorCode.ValidationError, $"Mentod with id {mentorId} is not Found");
Do the same fix as in line 104

2021-01-04 16:24 UTC, filinskyi commented on CharlieBackend.Api/Controllers/LessonsController.cs
> +
Remove this blank line

2021-01-09 15:29 UTC, Hlib-mats requested changes

2021-01-09 15:29 UTC, Hlib-mats commented on CharlieBackend.Api.UnitTes/MentorServiceTests.cs
> +                _notificationServiceMock.Object, lessonServiceMock.Object);
lessonServiceMock.Object must be on a next line and change variable name to _lessonServiceMock

2021-01-11 07:57 UTC, filinskyi commented on CharlieBackend.Data/Repositories/Impl/LessonRepository.cs
> +        public async Task<List<Lesson>> GetAllLessonsForMentor(long mentodId)
fix argument name from "mentodId" to "mentorId"

2021-01-11 07:58 UTC, filinskyi commented on CharlieBackend.Data/Repositories/Impl/Interfaces/ILessonRepository.cs
> +        Task<List<Lesson>> GetAllLessonsForMentor(long mentodId);
fix argument name from "mentodId" to "mentorId"

2021-01-11 08:05 UTC, filinskyi requested changes
small fix needed

2021-01-11 09:31 UTC, filinskyi approved these changes

2021-01-11 11:40 UTC, Hlib-mats approved these changes

2021-01-11 13:12 UTC, CptHouston approved these changes

2021-01-16 08:55 UTC, merged