add  new endpoint getAllActiveCourses
ita-social-projects/WhatBackend pull request #305
Opened 2021-01-14 15:23 UTC by QuestroL

2021-01-14 17:09 UTC, filinskyi requested changes
a query simplification and method naming

2021-01-14 17:09 UTC, filinskyi commented on CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
> +        public async Task<IList<Course>> GetAllActiveCourses()
due to the naming convention please provide ”Async” suffix to the end of the method name.

2021-01-14 17:09 UTC, filinskyi commented on CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
> +                .Select(x => x)
this query can be simplified, due to type of the parameter isActive is bool we can use it as a predicate for the Where method, and also Select part is don’t needed.
Code: .Where(x => x.IsActive)

2021-01-15 13:07 UTC, filinskyi approved these changes

2021-01-18 07:24 UTC, Hlib-mats commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +        [Authorize(Roles = "Admin, Mentor, Secretary, Student")]
What abouat swagger examples?

2021-01-24 09:44 UTC, Hlib-mats approved these changes

2021-01-24 18:54 UTC, gingerbread-monster commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +        [HttpGet("isAvtive")]
typo
```suggestion
        [HttpGet("isActive")]
```

2021-01-24 18:57 UTC, gingerbread-monster commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +        /// Gets cources
```suggestion
        /// Gets courses
```

2021-01-24 19:07 UTC, gingerbread-monster commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +        public async Task<IList<CourseDto>> GetCourses(bool? isActive)
* `activeOnly` should be a more suitable and descriptive name for this argument
* please add parameter description:
```cs
/// <param name="activeOnly">description</param>
```

2021-01-26 22:47 UTC, gingerbread-monster approved these changes

2021-01-26 22:50 UTC, gingerbread-monster commented on CharlieBackend.Api/Controllers/CoursesController.cs
> +        /// 3. If IsActive null method return all courses. </param>
Minor grammar corrections
```suggestion
        /// 1. If IsActive is true – method returns all active Courses.
        /// 2. If IsActive is false – method returns all not active Courses.
        /// 3. If IsActive is null – method returns all courses. </param>
```

2021-01-27 07:31 UTC, merged