Validation of ids was fixed. Two extension methods were added
ita-social-projects/WhatBackend pull request #332
Opened 2021-01-21 16:21 UTC by TetianaDomanska-dev

2021-01-22 01:37 UTC, filinskyi requested changes

2021-01-22 01:37 UTC, filinskyi commented on CharlieBackend.Core/Extensions/EnumerableExtensions.cs
> +        }
Why we need this extension? Instead of it we can use generic version of string.Join method.

2021-01-22 01:37 UTC, filinskyi commented on CharlieBackend.Core/Extensions/EnumerableExtensions.cs
> +        public static IEnumerable<T> Dublicates<T>(this IEnumerable<T> list)
argument name ”list” better change to “source” or “values”.

2021-01-29 13:00 UTC, gingerbread-monster commented
> _No description provided._
Please, always provide description of your changes.

2021-02-02 12:32 UTC, QuestroL approved these changes

2021-02-02 13:13 UTC, Hlib-mats approved these changes

2021-02-02 14:52 UTC, TetianaDomanska-dev commented
> > _No description provided._
> 
> Please, always provide description of your changes.

Ok

2021-02-02 23:25 UTC, gingerbread-monster approved these changes

2021-02-03 08:49 UTC, TetianaDomanska-dev commented
> > _No description provided._
> 
> Please, always provide description of your changes.

Ok

2021-02-03 12:56 UTC, andy-dendy-repo approved these changes

2021-02-03 18:21 UTC, Fizik97 approved these changes

2021-02-04 13:54 UTC, filinskyi reviewed
dublicates**Entity**.Count<long>() != 0  simplify to  dublicates**Entity**.Any()

2021-02-04 14:40 UTC, CptHouston approved these changes

2021-02-04 15:14 UTC, filinskyi approved these changes

2021-02-04 15:15 UTC, merged