Create CurrentUserTests.cs
ita-social-projects/WhatBackend pull request #504
Opened 2021-06-05 18:04 UTC by Pasha1968

Created CurrentUserTests.cs - tests for CurrentUserService.cs

2021-06-06 10:51 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            var mockIdentity = new Mock<GenericIdentity>("Vasya");
I think you can move this repetitive boilerplate code from each test method into `CurrentUserTests` class constructor, can't you?

2021-06-06 10:57 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            Assert.Equal("Hello@mail.com", Email);
Also I think we're supposed to use **FluentAssertions** for tests. You can view `MentorServiceTests` for reference.

e.g.:
https://github.com/ita-social-projects/WhatBackend/blob/899f397be4e51f81fc156f059c3ced0a0a60d669/CharlieBackend.Api.UnitTes/MentorServiceTests.cs#L65

2021-06-06 16:30 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            _httpContextAccessorMock.Setup(req => req.HttpContext).Returns(_httpContext);
Aren't these 2 lines can be moved from each method into constructor as well? :)

2021-06-06 16:30 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            Action act = () => getId();
Why add redundant delegates? Wouldn't it already work with the first one?

```suggestion
            Func<long> act = () => _currentuserService.AccountId;
```

2021-06-06 16:30 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            _currentuserService.AccountId.Should().Be(123);
When introducing expected values as constants, what I would suggest is declaring them in a single place (at least in the `Arrange` section of the test). This way you're decreasing the possibility of making a mistake and making code more "fluent".
Something like this:

```cs
            // Arrange
            long expectedAccountId = 123;
            
            _mockIdentity.Setup(i => i.Claims)
                .Returns(new Claim[]{
                    new Claim("AccountId", expectedAccountId.ToString()) 
                });

            // Act & Assert
            _currentuserService.AccountId.Should().Be(expectedAccountId);
```

This comment also applies to other methods & constants of yours.

2021-06-06 16:30 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            var mockIdentity = new Mock<GenericIdentity>("Vasya");
Partially solved in https://github.com/ita-social-projects/WhatBackend/pull/504/commits/e24ea4bfff6c941a77091f4f006367542332ab6b

2021-06-06 16:30 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            Assert.Equal("Hello@mail.com", Email);
Solved in https://github.com/ita-social-projects/WhatBackend/pull/504/commits/e24ea4bfff6c941a77091f4f006367542332ab6b

2021-06-07 10:15 UTC, andrii-developer commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +        public void ThrowErrorIfNotLoggined()
Please try to follow [best practices](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-PBLgRQP1_o9AbEiA2hJ8zg&epi=a1LgFw09t88-PBLgRQP1_o9AbEiA2hJ8zg&irgwc=1&OCID=AID2000142_aff_7806_1243925&tduid=%28ir__nnr3tb2a2okfqj1hkk0sohz3132xusa63bxexe1w00%29%287806%29%281243925%29%28a1LgFw09t88-PBLgRQP1_o9AbEiA2hJ8zg%29%28%29&irclickid=_nnr3tb2a2okfqj1hkk0sohz3132xusa63bxexe1w00#naming-your-tests) for naming of your tests. 
Please rename test methods like this one:
```suggestion
        public void AccountId_UserNotLoggedIn_ThrowsUnauthorizedAccessException()
```

2021-06-07 10:19 UTC, andrii-developer commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +        public void getAccountId()
Please follow [C# coding conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions). 
When naming public members of types, such as fields, properties, events, methods, and local functions, use pascal casing.

2021-06-07 10:22 UTC, andrii-developer commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +        }
Please add one blank line between methods.

2021-06-07 10:25 UTC, andrii-developer requested changes
Waiting for the author to address comments.

2021-06-07 10:28 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
>          public void getEntityId()
You're the first person I see to completely ignore the coding style of the rest of the project  and use _camelCase_ methods naming. 
Come on, it's not JavaScript. We use _PascalCase_ naming in C#.

Even better if you'd follow [the unit test naming convention](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#naming-your-tests). You can also look at other unit tests for reference.

2021-06-07 10:31 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
>          public void getEntityId()
Duplicate of https://github.com/ita-social-projects/WhatBackend/pull/504#discussion_r646455509

2021-06-07 10:34 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            _currentuserService.AccountId.Should().Be(123);
Solved in https://github.com/ita-social-projects/WhatBackend/pull/504/commits/599f172a458febfc3f38a1fd66639d04ac39d823

2021-06-07 10:34 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            Action act = () => getId();
Solved in https://github.com/ita-social-projects/WhatBackend/pull/504/commits/599f172a458febfc3f38a1fd66639d04ac39d823

2021-06-07 10:35 UTC, gingerbread-monster commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +            _httpContextAccessorMock.Setup(req => req.HttpContext).Returns(_httpContext);
Solved in https://github.com/ita-social-projects/WhatBackend/pull/504/commits/599f172a458febfc3f38a1fd66639d04ac39d823

2021-06-07 11:26 UTC, andrii-developer commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +
Remove empty lines between [Fact] attribute and methods.

2021-06-07 11:33 UTC, andrii-developer commented on CharlieBackend.Api.UnitTes/CurrentUserTests.cs
> +
Remove this empty line.

2021-06-07 11:37 UTC, andrii-developer approved these changes

2021-06-07 11:46 UTC, gingerbread-monster approved these changes

2021-06-14 08:09 UTC, DemetriosKorass approved these changes

2021-06-26 20:30 UTC, merged