changed enable/disable course logic
ita-social-projects/WhatBackend pull request #565
Opened 2021-07-23 11:05 UTC by KSudak

2021-07-27 12:36 UTC, DemetriosKorass approved these changes

2021-07-30 11:11 UTC, andrii-developer requested changes

2021-07-30 11:11 UTC, andrii-developer commented on CharlieBackend.Business/Services/CourseService.cs
> +        {
Please remove these spaces.

2021-07-30 11:11 UTC, andrii-developer commented on CharlieBackend.Data/Repositories/Impl/CourseRepository.cs
> +                return null;
Why do we change this? I think we could return Resunt with Error and check that error in places where we call this method.

2021-08-02 17:38 UTC, andrii-developer approved these changes

2021-08-03 13:50 UTC, Vso1o approved these changes

2021-08-03 13:50 UTC, Ilhamich approved these changes

2021-08-03 14:07 UTC, Tkachelnik approved these changes

2021-08-03 14:14 UTC, merged