Add attribute to ErrorDTO
ita-social-projects/WhatBackend pull request #580
Opened 2021-08-01 19:10 UTC by Tkachelnik

2021-08-02 16:12 UTC, andrii-developer approved these changes

2021-08-04 10:09 UTC, andrii-developer requested changes
As it was agreed on a meeting. The FluentValidation response model should be converted to our common model.

2021-08-11 13:05 UTC, andrii-developer approved these changes
Everything is fine. Just a few cosmetic comments. Please address them before the merge.

2021-08-11 13:05 UTC, andrii-developer commented on CharlieBackend.Core/DTO/Result/ErrorDto.cs
> +using Newtonsoft.Json;
Please remove that using.

2021-08-11 13:05 UTC, andrii-developer commented on CharlieBackend.AdminPanel/Middlewares/ExceptionHandleMiddleware.cs
> +                var encodeMessage = HttpUtility.UrlEncode(ex.Message);
encodedMessage

2021-08-11 13:05 UTC, andrii-developer commented on CharlieBackend.AdminPanel/Controllers/HomeController.cs
> +            var decodeMessage = HttpUtility.UrlDecode(message);
decodedMessage

2021-08-11 17:48 UTC, Vso1o approved these changes

2021-08-17 13:33 UTC, KSudak approved these changes

2021-08-19 07:32 UTC, Ilhamich approved these changes

2021-08-19 12:14 UTC, DemetriosKorass approved these changes

2021-08-25 08:30 UTC, elizabeth-grant-20 approved these changes

2021-08-26 14:14 UTC, merged