Fix bug at AdminPanel ApiUtils
ita-social-projects/WhatBackend pull request #582
Opened 2021-08-02 10:34 UTC by Tkachelnik

2021-08-02 16:11 UTC, andrii-developer requested changes
Please change TResponce to TResponse.

2021-08-03 13:04 UTC, DemetriosKorass approved these changes

2021-08-03 13:04 UTC, andrii-developer approved these changes

2021-08-03 13:04 UTC, elizabeth-grant-20 approved these changes

2021-08-03 13:05 UTC, Ilhamich approved these changes

2021-08-03 13:06 UTC, KSudak approved these changes

2021-08-04 07:55 UTC, merged