Dashboard feature reimplementation
ita-social-projects/WhatBackend pull request #590
Opened 2021-08-05 12:03 UTC by Vso1o

Resolves #589 and #547

2021-08-06 15:06 UTC, DemetriosKorass approved these changes

2021-08-07 11:28 UTC, Ilhamich approved these changes

2021-08-09 08:12 UTC, AnnBazille approved these changes

2021-08-10 13:32 UTC, KSudak approved these changes

2021-08-10 19:49 UTC, andrii-developer requested changes

2021-08-10 19:49 UTC, andrii-developer commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/ClassbookExport.cs
> +                xLWorkbook.AddWorksheet("Presence of " + data.StudentsPresences.First().StudentGroup);
Please extract the data.StudentsPresences.First().StudentGroup into a variable. As you use it many times.

2021-08-10 19:49 UTC, andrii-developer commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/ClassbookExport.cs
> +                for (int student = 0; student < studentList.Count(); student++)
I would rename it to studentIndex or something like that.

2021-08-10 19:49 UTC, andrii-developer commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/ClassbookExport.cs
> +                int presencesGroups = dateData.Count();
presenceGroupsCount.

2021-08-11 08:50 UTC, andrii-developer approved these changes

2021-08-11 08:58 UTC, merged