added condition for email
ita-social-projects/WhatBackend pull request #606
Opened 2021-08-12 07:23 UTC by KSudak

2021-08-12 08:05 UTC, Ilhamich approved these changes

2021-08-12 08:34 UTC, andrii-developer requested changes

2021-08-12 08:34 UTC, andrii-developer commented on CharlieBackend.Api/Controllers/AccountsController.cs
> +            var email = claim.FirstOrDefault(x => x.Type == "Email");
Use the ClaimConstants.EmailClaim constant for claim type instead of "Email".

2021-08-12 08:37 UTC, andrii-developer commented
I would remove Email property from the request. User can change password for their own account only.

2021-08-20 04:28 UTC, DemetriosKorass approved these changes

2021-08-20 18:32 UTC, andrii-developer approved these changes

2021-08-23 08:51 UTC, AnnBazille approved these changes

2021-08-23 10:22 UTC, Tkachelnik approved these changes

2021-08-23 10:23 UTC, merged