add unit test
ita-social-projects/WhatBackend pull request #640
Opened 2021-08-31 12:15 UTC by KSudak

2021-08-31 16:24 UTC, elizabeth-grant-20 approved these changes

2021-09-01 13:05 UTC, DemetriosKorass approved these changes

2021-09-06 12:48 UTC, Vso1o requested changes
Unit test also should contain case of linking lesson already linked to another ScheduledEvent

2021-09-22 11:27 UTC, Vso1o approved these changes

2021-09-22 11:42 UTC, DmitriyFesak approved these changes

2021-09-22 13:37 UTC, andrii-developer approved these changes

2021-09-22 18:18 UTC, merged