Student groups deletion functionality
ita-social-projects/WhatBackend pull request #660
Opened 2021-09-14 13:36 UTC by DmitriyFesak

2021-09-15 13:43 UTC, andrii-developer requested changes

2021-09-15 13:43 UTC, andrii-developer commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +            var allStudentGroups = await _unitOfWork.StudentGroupRepository.GetAllAsync();
Please implement GetAllActive() method in the repository and use it instead of GetAllAsync() + HideUnactiveStudentGroups

2021-09-15 13:43 UTC, andrii-developer commented on CharlieBackend.Data/Repositories/Impl/LessonRepository.cs
> +                .Select(lesson => lesson)
Please remove .Select

2021-09-15 13:43 UTC, andrii-developer commented on CharlieBackend.Data/Repositories/Impl/StudentGroupRepository.cs
> +                _applicationContext.SaveChanges();
Please remove .SaveChanges and call it from _unitOfWork

2021-09-15 13:43 UTC, andrii-developer commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +                return Result<StudentGroupDto>.GetError(ErrorCode.NotFound, "Student group is unactive or does not exist.");
Unactive -> Inactive.

2021-09-16 12:47 UTC, andrii-developer approved these changes

2021-09-17 13:12 UTC, Ilhamich approved these changes

2021-09-17 13:14 UTC, elizabeth-grant-20 approved these changes

2021-09-17 13:18 UTC, AnnBazille approved these changes

2021-09-17 13:40 UTC, Tkachelnik approved these changes

2021-09-17 13:41 UTC, merged