Added new endpoint(GetStudentHomeworkInGroup)
ita-social-projects/WhatBackend pull request #668
Opened 2021-09-19 14:11 UTC by KSudak

2021-10-05 13:38 UTC, andrii-developer requested changes

2021-10-05 13:38 UTC, andrii-developer commented on CharlieBackend.Api/Controllers/HomeworkStudentController.cs
> +        [HttpGet]
HttpGet("done")

2021-10-29 14:11 UTC, elizabeth-grant-20 approved these changes

2021-11-03 13:36 UTC, Tkachelnik approved these changes

2021-11-11 10:00 UTC, andrii-developer approved these changes

2021-11-12 15:28 UTC, DmitriyFesak approved these changes

2021-11-15 08:00 UTC, MakhortovSasha approved these changes

2021-11-25 10:58 UTC, merged