Student groups merging and deletion enhancements
ita-social-projects/WhatBackend pull request #674
Opened 2021-09-20 13:47 UTC by DmitriyFesak

2021-09-22 13:58 UTC, andrii-developer requested changes

2021-09-22 13:58 UTC, andrii-developer commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +                result = _unitOfWork.StudentGroupRepository.DeactivateStudentGroupAsync(StudentGroupId).Result;
Use await instead of Result.

2021-09-22 13:58 UTC, andrii-developer commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +                var scheduledEvents = _scheduleService.GetEventOccurrencesByGroupIdAsync(StudentGroupId).Result;
Use await instead of Result.

2021-10-05 13:24 UTC, andrii-developer approved these changes

2021-10-05 13:26 UTC, elizabeth-grant-20 approved these changes

2021-10-05 13:27 UTC, Ilhamich approved these changes

2021-10-05 13:29 UTC, Q-Alex-Q approved these changes

2021-10-05 13:51 UTC, Vso1o approved these changes

2021-10-05 13:51 UTC, KSudak approved these changes

2021-10-05 13:51 UTC, merged