Enhancement GetAllLessons endpoint
ita-social-projects/WhatBackend pull request #677
Opened 2021-09-21 19:58 UTC by KSudak

2021-09-22 14:06 UTC, andrii-developer requested changes

2021-09-22 14:06 UTC, andrii-developer commented on CharlieBackend.Api/Controllers/LessonsController.cs
> +        [HttpGet("DateTime")]
Please remove "DateTime". Also make the startDate and finishDate parameters optional.

2021-09-22 14:06 UTC, andrii-developer commented on CharlieBackend.Data/Repositories/Impl/LessonRepository.cs
> +        public Task<List<Lesson>> GetLessonsByDate(DateTime? startDate, DateTime? finishDate, long daysWeek, DateTime lastLessonDate)
Please remove dayWeek and lastlessonDate parameters and implement that logic in the LessonService.GetLessonsByDate method.

2021-09-22 14:06 UTC, andrii-developer commented on CharlieBackend.Business/Services/LessonService.cs
> +            var lastLesson = await _unitOfWork.LessonRepository.GetLastLesson();
If startDate and finishDate are null then compute them as you do in the repository.

2021-09-22 23:03 UTC, andrii-developer approved these changes

2021-09-22 23:10 UTC, elizabeth-grant-20 approved these changes

2021-09-23 06:46 UTC, Ilhamich approved these changes

2021-09-23 06:52 UTC, AnnBazille approved these changes

2021-09-23 07:02 UTC, Tkachelnik approved these changes

2021-09-23 07:03 UTC, merged