Add new endpoint get not complited homeworks
ita-social-projects/WhatBackend pull request #688
Opened 2021-09-28 12:26 UTC by KSudak

2021-10-01 14:18 UTC, Tkachelnik commented on CharlieBackend.Business/Services/HomeworkService.cs
> +        public async Task<Result<IList<HomeworkDto>>> GetHomeworkNotDone(long studentGroup)
Rename parameter 'studentGroup' to 'studentGroupId'

2021-10-01 14:22 UTC, Tkachelnik commented on CharlieBackend.Business/Services/HomeworkService.cs
> +            var homeworIdList =  await _unitOfWork.HomeworkStudentRepository.GetIdsHomework(studentGroup,student.Id);
You lose letter 'k' at 'homeworIdList
'

2021-10-01 14:25 UTC, Tkachelnik commented on CharlieBackend.Business/Services/HomeworkService.cs
> +            var group = await _unitOfWork.StudentGroupRepository.GetStudentGroupsIdsByStudentId(student.Id);
Rename 'group' to something like 'studentGroupsIds'

2021-10-05 13:36 UTC, andrii-developer requested changes

2021-10-05 13:36 UTC, andrii-developer commented on CharlieBackend.Business/Services/HomeworkService.cs
> +                dueDate = dueDate.Value.AddDays(1);
...Value.Date.AddDays...

2021-10-05 13:36 UTC, andrii-developer commented on CharlieBackend.Business/Services/HomeworkService.cs
> +            var studentGroupsIds = await _unitOfWork.StudentGroupRepository.GetStudentGroupsIdsByStudentId(student.Id);
Instead of student.Id get it from _currentUserService.EntityId.

2021-10-05 13:36 UTC, andrii-developer commented on CharlieBackend.Data/Repositories/Impl/HomeworkRepository.cs
> +                .Where(x => x.Lesson.StudentGroup.Id == studentGroupId && !studentHomeworkIds.Contains(x.Id))
.Where(h=>!h.HomeworkStudents.Any(hs=>hs.StudentId == studentId || !hs.IsSent))

2021-10-05 13:36 UTC, andrii-developer commented on CharlieBackend.Data/Repositories/Impl/HomeworkRepository.cs
> +        public async Task<IList<Homework>> GetNotDoneHomeworksByStudentGroup(long studentGroupId, List<long> studentHomeworkIds, DateTime? dueDate)
Pass studentId instead of studentHomeworkIds.

2021-10-12 20:03 UTC, andrii-developer approved these changes

2021-10-13 08:49 UTC, maksymiu4e approved these changes

2021-10-13 08:50 UTC, Tkachelnik approved these changes

2021-10-13 09:30 UTC, elizabeth-grant-20 approved these changes

2021-10-13 09:35 UTC, AnnBazille approved these changes

2021-10-13 09:38 UTC, merged