Adding Notification to TG-bot
ita-social-projects/WhatBackend pull request #716
Opened 2021-10-13 15:50 UTC by Tkachelnik

2021-10-13 17:20 UTC, andrii-developer requested changes

2021-10-13 17:20 UTC, andrii-developer commented on CharlieBackend.Business/Services/Notification/HangfireJobService.cs
> +            return jobId != null ? true : false;
`return jobId != null;` - that is enough.

2021-10-13 17:20 UTC, andrii-developer commented on CharlieBackend.Business/Services/Notification/HangfireJobService.cs
> +            return jobId != null ? true : false;
`return jobId != null;` - that is enough.

2021-10-13 17:20 UTC, andrii-developer commented on CharlieBackend.Business/Services/Notification/HangfireJobService.cs
> +            return jobId != null ? true : false;
`return jobId != null;` - that is enough.

2021-10-13 17:20 UTC, andrii-developer commented on CharlieBackend.Data/ApplicationContext.cs
> +﻿ using CharlieBackend.Core.Entities;
Please remove the space.

2021-10-13 17:20 UTC, andrii-developer commented on CharlieBackend.Root/CompositionRoot.cs
> +                      //b.EnableRetryOnFailure(5, TimeSpan.FromSeconds(10), null);
Please remove the commented code.

2021-10-13 17:20 UTC, andrii-developer commented on WhatBackend.TelegramBotApi/Controllers/MessageController.cs
> +            if(DateTime.Now >= new DateTime(2021,10,13,17,30, 1))
What is the purpose of that code?

2021-10-13 17:20 UTC, andrii-developer commented on WhatBackend.TelegramBotApi/Startup.cs
> +        private DbConnection ApiSettings()
What is the purpose of that method?

2021-10-13 19:08 UTC, andrii-developer approved these changes

2021-10-13 19:27 UTC, Ilhamich approved these changes

2021-10-14 09:50 UTC, DmitriyFesak approved these changes

2021-10-14 11:11 UTC, Q-Alex-Q approved these changes

2021-10-19 13:18 UTC, merged