#710 lesson controller to what panel
ita-social-projects/WhatBackend pull request #760
Opened 2021-12-08 09:26 UTC by maksymiu4e

2021-12-19 11:08 UTC, AccorDDD approved these changes
All looks good, but on my mind too many changes for one issue

2021-12-19 11:10 UTC, leshikevich approved these changes

2021-12-20 11:43 UTC, BobTheSuperman commented on CharlieBackend.Panel/Services/StudentGroupService.cs
> +            if (!(_currentUserService.Role == Core.Entities.UserRole.Mentor))
Not a very clear condition, in my opinion it's more understandable
if (_currentUserService.Role != Core.Entities.UserRole.Mentor)

2021-12-20 12:14 UTC, BobTheSuperman approved these changes
In my opinion, it is necessary to change the names of some variables.

2021-12-20 12:14 UTC, BobTheSuperman commented on CharlieBackend.Panel/Views/Lessons/Attendance.cshtml
> +                                        }
I think it's better to use an if else construction than two if

2021-12-20 12:14 UTC, BobTheSuperman commented on CharlieBackend.Panel/Views/Lessons/Events.cshtml
> +                                @foreach (var item in @Model)
It is not clear from the name what item stores in itself.

2021-12-20 12:14 UTC, BobTheSuperman commented on CharlieBackend.Panel/Views/Lessons/GroupSelection.cshtml
> +                            @foreach (var item in Model)
Again "item"

2021-12-23 14:07 UTC, ArsenMaistryshyn requested changes

2021-12-23 14:07 UTC, ArsenMaistryshyn commented on CharlieBackend.Data/Configurations/VisitEntityConfiguration.cs
> +                //.HasDefaultValueSql("1")
please explain why this is commented and if it is not needed then delete it.

2021-12-23 14:07 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Services/LessonService.cs
> +        public async Task<LessonDto> GetLessonById(long id)
please add asyn everywhere if method is async.

2021-12-23 14:07 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Controllers/LessonsController.cs
> +
please remove space

2021-12-23 14:07 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Models/Mapping/ViewModelMapping.cs
> +                Select(y => new  VisitDto
please remove select and fix mapping

2021-12-23 14:07 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Models/Mapping/ViewModelMapping.cs
> +            CreateMap<ScheduledEventViewModel, ScheduledEventDTO>();
please use reverse map

2021-12-23 14:07 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Services/EventsService.cs
> +        public EventsService(IOptions<ApplicationSettings> options,
please add spaces where needed.

2021-12-23 15:06 UTC, ArsenMaistryshyn approved these changes

2022-01-26 13:57 UTC, merged