764 feature html export
ita-social-projects/WhatBackend pull request #776
Opened 2022-01-17 02:02 UTC by BobTheSuperman

2022-01-17 13:11 UTC, AccorDDD commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +        }
Why is this constructor here?

2022-01-17 13:11 UTC, AccorDDD approved these changes

2022-01-18 12:20 UTC, leshikevich approved these changes

2022-01-18 13:14 UTC, Ssashaa approved these changes

2022-01-18 13:21 UTC, Soctarian approved these changes

2022-01-24 14:06 UTC, ArsenMaistryshyn requested changes

2022-01-24 14:06 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Helpers/HtmlGenerator.cs
> +
please remove space

2022-01-24 14:06 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/ExportServiceHtml.cs
> +
please remove space

2022-01-24 14:06 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/ExportServiceHtml.cs
> +                        "Group not found");
please extract to response messages

2022-01-24 14:06 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +        private void TryToFillMarks(StudentsClassbookResultDto data)
please rename to fill marks

2022-01-24 14:06 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +                string[] headers = new string[dateData.Count() + 2];
please leave a comment

2022-01-24 14:06 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +                    List<int> listOfMarks = new List<int>();
please rename

2022-01-24 14:06 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +                            listOfMarks.Add(Convert.ToInt32(rows[i][j + 1]));
please rework according to conversation

2022-01-24 14:06 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +            return $"Group: {group} {startDate}&nbsp;-&nbsp;{finishDate}";
please move to constants

2022-01-25 23:39 UTC, BobTheSuperman commented on CharlieBackend.Business/Helpers/HtmlGenerator.cs
> +
Done!

2022-01-25 23:40 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/ExportServiceHtml.cs
> +
Done!

2022-01-25 23:41 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +        private void TryToFillMarks(StudentsClassbookResultDto data)
Done!

2022-01-26 00:10 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +                    List<int> listOfMarks = new List<int>();
Done

2022-01-26 00:10 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +                            listOfMarks.Add(Convert.ToInt32(rows[i][j + 1]));
Done!

2022-01-28 12:41 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +        }
Removed it, ty.

2022-01-28 14:55 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/ExportServiceHtml.cs
> +                        "Group not found");
Done

2022-01-28 15:00 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +            return $"Group: {group} {startDate}&nbsp;-&nbsp;{finishDate}";
Done!

2022-01-28 15:00 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookExportHTML.cs
> +                string[] headers = new string[dateData.Count() + 2];
Done!

2022-02-01 14:59 UTC, ArsenMaistryshyn approved these changes

2022-02-01 21:23 UTC, merged