Added access to mentor tab for mentors.
ita-social-projects/WhatBackend pull request #786
Opened 2022-02-01 12:50 UTC by BobTheSuperman

2022-02-02 11:17 UTC, DmitryTkachenko approved these changes

2022-02-02 13:46 UTC, Ssashaa approved these changes

2022-02-02 13:49 UTC, ArsenMaistryshyn requested changes

2022-02-02 13:49 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Controllers/MentorsController.cs
> +            IEnumerable<MentorViewModel> mentor = null;
please return empty list

2022-02-02 13:49 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Services/MentorService.cs
> +                mentor.IsActive = true;
please check IsActive property. Investigate ActiveMentorEndpoint.

2022-02-04 13:23 UTC, BobTheSuperman commented on CharlieBackend.Panel/Services/MentorService.cs
> +                mentor.IsActive = true;
thx

2022-02-04 13:23 UTC, BobTheSuperman commented on CharlieBackend.Panel/Controllers/MentorsController.cs
> +            IEnumerable<MentorViewModel> mentor = null;
thx

2022-02-04 13:30 UTC, ArsenMaistryshyn approved these changes

2022-02-04 14:08 UTC, marinapelin approved these changes

2022-02-04 14:09 UTC, apyura approved these changes

2022-02-07 11:47 UTC, merged