785 feature redesign export architecture
ita-social-projects/WhatBackend pull request #805
Opened 2022-02-21 12:11 UTC by BobTheSuperman

2022-02-23 14:05 UTC, Ssashaa approved these changes

2022-03-02 13:50 UTC, ArsenMaistryshyn requested changes

2022-03-02 13:50 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Csv/CsvFileExport.cs
> +        protected virtual byte[] ConvertLineToArray(string line)
please make extension

2022-03-03 13:12 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Csv/CsvFileExport.cs
> +        protected virtual byte[] ConvertLineToArray(string line)
Done, thx.

2022-03-11 13:16 UTC, ArsenMaistryshyn requested changes

2022-03-11 13:16 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/StudentGroupsHtmlFileExport.cs
>          private const int _FirstNameColumnNumber = 0;
please rename according to conventions

2022-03-11 13:58 UTC, apyura approved these changes

2022-03-11 15:53 UTC, ArsenMaistryshyn approved these changes

2022-03-16 23:53 UTC, merged