777 Implemented feature for export student class book in html format
ita-social-projects/WhatBackend pull request #809
Opened 2022-02-28 00:10 UTC by BobTheSuperman

2022-03-02 13:33 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/StudentClassbookExportHTML.cs
> +        private const int _FifthColumn = 4;
Enum

2022-03-02 13:33 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/StudentClassbookExportHTML.cs
> +                    rows[i][_FourthColumn] = studentVisits.ElementAt(i).Presence == null ? " " : studentVisits.ElementAt(i).Presence == true ? $"&#10003;" : " ";
✓(&#10003;) add to html constants

2022-03-02 13:40 UTC, ArsenMaistryshyn requested changes

2022-03-02 13:40 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/StudentClassbookExportHTML.cs
> +            return $"Student {student} results {startDate}{HtmlGenerator.NonBreakingSpace}{finishDate}";
please move to constants

2022-03-02 13:40 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/StudentClassbookExportHTML.cs
> +                    rows[i][_FourthColumn] = studentVisits.ElementAt(i).Presence == null ? " " : studentVisits.ElementAt(i).Presence == true ? $"&#10003;" : " ";
please format

2022-03-02 13:52 UTC, Ssashaa approved these changes

2022-03-03 16:02 UTC, BobTheSuperman commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/StudentClassbookExportHTML.cs
> +                    rows[i][_FourthColumn] = studentVisits.ElementAt(i).Presence == null ? " " : studentVisits.ElementAt(i).Presence == true ? $"&#10003;" : " ";
Done, thx.

2022-03-11 13:20 UTC, ArsenMaistryshyn requested changes

2022-03-11 13:20 UTC, ArsenMaistryshyn commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/StudentClassbookExportHTML.cs
> +    internal class StudentClassbookExportHTML : BaseFileExportHTML
please make public

2022-03-11 13:30 UTC, da-real-ivanpan approved these changes

2022-03-11 13:56 UTC, ArsenMaistryshyn approved these changes

2022-03-11 14:32 UTC, merged