#748 add oportunity for getting classbook in panel
ita-social-projects/WhatBackend pull request #841
Opened 2022-04-11 19:46 UTC by DmitryTkachenko

2022-04-13 12:28 UTC, ArsenMaistryshyn requested changes

2022-04-13 12:28 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Controllers/ClassbookController.cs
> +using CharlieBackend.Panel.Services.Interfaces;
please remove

2022-04-13 12:28 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Controllers/ClassbookController.cs
> +using Microsoft.AspNetCore.Authorization;
please remove

2022-04-13 12:28 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Controllers/ClassbookController.cs
> +        public async Task<IActionResult> GetClassbook(StudentsRequestDto<ClassbookResultType> scheduledEventFilter)
please add async to naming

2022-04-13 12:28 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +            if (classbookFilter.StartDate==default(DateTime))
please add space

2022-04-13 12:28 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +            if (classbookFilter.FinishDate==default(DateTime))
same here and in next

2022-04-13 12:28 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +        private async Task<FilteredClassbookViewModel> GetFilteredRegisterViewModelAsynk(
please rename asynk => async

2022-04-13 12:28 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +            var result = await _apiUtil.PostAsync< StudentsClassbookResultDto, StudentsRequestDto <ClassbookResultType>>(
please remove space

2022-04-13 12:28 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Services/Interfaces/IClassbookService.cs
> +    /// Interface that describes methods for work with classbook and it's data.
please fix it's => its

2022-04-15 12:27 UTC, BobTheSuperman approved these changes

2022-04-15 12:27 UTC, BobTheSuperman commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +            StudentsRequestDto<ClassbookResultType> classbookFilter)
add a second indent (+4 spaces)

2022-04-15 12:27 UTC, BobTheSuperman commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +                await _apiUtil.GetAsync<IList<StudentGroupDto>>(_getStudentGroupsEndpoint);
add a second indent (+4 spaces)

2022-04-15 12:27 UTC, BobTheSuperman commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +                data: groupsRegisterFilter);
add a second indent (+4 spaces)

2022-04-15 12:27 UTC, BobTheSuperman commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +                ClassbookResultType.StudentPresence, ClassbookResultType.StudentMarks };
Please format.

2022-04-18 12:10 UTC, Ssashaa approved these changes

2022-04-20 13:36 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Controllers/ClassbookController.cs
> +using CharlieBackend.Panel.Services.Interfaces;
Done

2022-04-22 17:47 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Controllers/ClassbookController.cs
> +using Microsoft.AspNetCore.Authorization;
Done

2022-04-22 17:48 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Controllers/ClassbookController.cs
> +        public async Task<IActionResult> GetClassbook(StudentsRequestDto<ClassbookResultType> scheduledEventFilter)
Done

2022-04-22 17:48 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +            if (classbookFilter.StartDate==default(DateTime))
Done

2022-04-22 17:48 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +            if (classbookFilter.FinishDate==default(DateTime))
Done

2022-04-22 17:48 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +        private async Task<FilteredClassbookViewModel> GetFilteredRegisterViewModelAsynk(
Done

2022-04-22 17:48 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +            var result = await _apiUtil.PostAsync< StudentsClassbookResultDto, StudentsRequestDto <ClassbookResultType>>(
Done

2022-04-22 17:49 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/Interfaces/IClassbookService.cs
> +    /// Interface that describes methods for work with classbook and it's data.
Done

2022-04-22 17:49 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +            StudentsRequestDto<ClassbookResultType> classbookFilter)
Done

2022-04-22 17:49 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +                await _apiUtil.GetAsync<IList<StudentGroupDto>>(_getStudentGroupsEndpoint);
Done

2022-04-22 17:49 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +                data: groupsRegisterFilter);
Done

2022-04-22 17:49 UTC, DmitryTkachenko commented on CharlieBackend.Panel/Services/ClassbookService.cs
> +                ClassbookResultType.StudentPresence, ClassbookResultType.StudentMarks };
Done

2022-04-26 12:41 UTC, da-real-ivanpan approved these changes

2022-04-26 13:00 UTC, SergeiKisa approved these changes

2022-04-27 12:17 UTC, ArsenMaistryshyn approved these changes

2022-04-27 12:17 UTC, ArsenMaistryshyn commented on CharlieBackend.Panel/Models/Classbook/FilteredClassbookViewModel.cs
> +            public IList<StudentMarkDto> StudentsMarks { get; set; }
please remove one space

2022-04-27 12:24 UTC, merged