Bugfix/860-861 Fix Unhandled Exceptions
ita-social-projects/WhatBackend pull request #863
Opened 2022-05-06 11:49 UTC by BohdanZaliubovskyi

Related issues: #860, #861 

fixed catch of the generated exception

2022-05-06 12:05 UTC, PavelTsyposhchuk requested changes

2022-05-06 12:05 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Utils/ApiUtil.cs
> +        private async Task EnsureSuccessStatusCode(HttpResponseMessage httpResponse)
In yesterday's meeting looks like we agreed to add the async suffix to async methods, didn`t it?

2022-05-06 12:05 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Utils/ApiUtil.cs
> +            if(message != string.Empty)
Maybe IsNullOrEmpty would be better here? I know that this method returns string.empty, but still

2022-05-06 12:05 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Utils/HttpUtil.cs
> +                if (apiStringResponse != "")
IsNullOrEmptyOrWhiteSpace definetly would be better

2022-05-06 12:30 UTC, filinskyi commented on CharlieBackend.Panel/Utils/HttpUtil.cs
> +                return apiResponseMessage;
curly brackets for "if else" body, 
if condition replace "" to string.Empty,
and it is possible to simplify it as inline return or assigned to the variable "apiResponseMessage" 
```
return apiStringResponse != string.Empty 
          ? JsonConvert.DeserializeObject<ErrorDto>(apiStringResponse).Error.Message
          : ErrorsConstants.EmptyApiStringResponse;
```

2022-05-06 12:41 UTC, filinskyi approved these changes
LGTM

2022-05-06 12:51 UTC, PavelTsyposhchuk approved these changes

2022-05-06 16:07 UTC, DevPew01 approved these changes

2022-05-09 09:31 UTC, andy-dendy-repo approved these changes

2022-05-09 09:37 UTC, Ssashaa approved these changes

2022-05-10 21:52 UTC, merged