Issue #851
ita-social-projects/WhatBackend pull request #877
Opened 2022-05-16 10:17 UTC by DevPew01

https://github.com/ita-social-projects/WhatBackend/issues/851#issue-1212256248

2022-05-16 13:59 UTC, apyura commented on CharlieBackend.Core/DTO/Schedule/UpdateScheduledEventDto.cs
> +    public class UpdateScheduledEventDto
please, remove empty space

2022-05-16 14:13 UTC, BohdanZaliubovskyi commented on CharlieBackend.Panel/Extensions/Extensions.cs
> +                client.BaseAddress = new Uri(configuration.GetSection("Urls:Api:Http").Value);
We need s)

2022-05-17 13:28 UTC, PavelTsyposhchuk requested changes
About SQL, I understand it right, that we need to drop and create DB to apply ur changes? Why u don`t add a script 11_color_bla_bla which updates the existing DB to the needed state?

2022-05-17 13:28 UTC, PavelTsyposhchuk commented on CharlieBackend.Api/Validators/ScheduleDTOValidators/CreateScheduleDTO/ContextForCreateScheduleDTOValidators.cs
> +            RuleFor(x => x.Color).NotNull();
I think we need expanded validation, I don't think that we can have int color with sign minus for example

2022-05-17 13:28 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
> +                    calendar.EventOccurences.FirstOrDefault(x => x.Id.Equals(scheduledEvent?.EventOccuranceId)).Color : scheduledEvent.Color
FirstOrDefault != null, always true, FirstOrDefult in case empty collections returns null as default as I know

2022-05-17 13:28 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Views/EventOccurrence/AddSingleEvent.cshtml
> +        });
IMHO need to extract the js code to js files

2022-05-17 13:28 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Views/EventOccurrence/AddEventOccurrence.cshtml
> +                $("#inputColor").val(this.color);
IMHO need to extract the js code to js files

2022-05-17 13:28 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Views/EventOccurrence/UpdateEventOccurrence.cshtml
> +    </script>
IMHO need to extract the js code to js files

2022-05-17 13:28 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Views/EventOccurrence/UpdateEventOccurrence.cshtml
> +    </script>
Moreover, it`s 3rd/4th piece of duplicated code

2022-05-17 13:28 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Views/EventOccurrence/UpdateSingleEvent.cshtml
> +</script>
same

2022-05-17 13:28 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/Views/Shared/_Layout.cshtml
> +    </style>
extract css to css file

2022-05-17 13:29 UTC, PavelTsyposhchuk commented on CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
> +                    calendar.EventOccurences.FirstOrDefault(x => x.Id.Equals(scheduledEvent?.EventOccuranceId)).Color : scheduledEvent.Color
My bad invalid question, forgot

2022-05-17 13:56 UTC, BohdanZaliubovskyi commented on CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
> +                    calendar.EventOccurences.FirstOrDefault(x => x.Id.Equals(scheduledEvent?.EventOccuranceId)).Color : scheduledEvent.Color
It seems like we call the same function 2 times, try something like this:
``` C#
Color currentColor = calendar.EventOccurences.FirstOrDefault(x => x.Id.Equals(scheduledEvent?.EventOccuranceId));
.....
Color = currentColor  ?? scheduledEvent.Color
```

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator

2022-05-17 15:10 UTC, DevPew01 commented on CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
> +                    calendar.EventOccurences.FirstOrDefault(x => x.Id.Equals(scheduledEvent?.EventOccuranceId)).Color : scheduledEvent.Color
Yes looks better. But we can't use any variables inside initializer(((

2022-05-17 16:45 UTC, BohdanZaliubovskyi commented on CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
> +                    calendar.EventOccurences.FirstOrDefault(x => x.Id.Equals(scheduledEvent?.EventOccuranceId)).Color : scheduledEvent.Color
```
private static IList<CalendarScheduledEventModel> GetScheduledEventModels(CalendarViewModel calendar, DateTime startDate, DateTime finishDate)
        {
            Color currentColor = calendar.EventOccurences.FirstOrDefault(x => x.Id.Equals(scheduledEvent?.EventOccuranceId));

            var models = calendar.ScheduledEvents.Where(i => i.EventStart >= startDate && i.EventFinish <= finishDate)
                .Select(scheduledEvent => new CalendarScheduledEventModel
                {
                    Theme = calendar.Themes.First(t => t.Id == scheduledEvent.ThemeId).Name,
                    MentorFirstName = calendar.Mentors.First(m => m.Id == scheduledEvent.MentorId).FirstName,
                    MentorLastName = calendar.Mentors.First(m => m.Id == scheduledEvent.MentorId).LastName,
                    StudentGroup = calendar.StudentGroups.First(s => s.Id == scheduledEvent.StudentGroupId).Name,
                    EventStart = scheduledEvent.EventStart,
                    EventFinish = scheduledEvent.EventFinish,
                    EventOccurrenceId = scheduledEvent.EventOccuranceId,
                    SingleEventId = scheduledEvent.Id,
                    Color = currentColor  ?? scheduledEvent.Color
                }).OrderBy(i => i.EventStart)
                .ToList();

            return models;
        }
```

2022-05-19 12:42 UTC, BobTheSuperman requested changes

2022-05-19 12:42 UTC, BobTheSuperman commented on CharlieBackend.Core/DTO/Schedule/EventOccurrenceDTO.cs
> +    public class EventOccurrenceDTO
Remove space please

2022-05-19 12:42 UTC, BobTheSuperman commented on CharlieBackend.Core/Mapping/ModelMappingProfile.cs
> +            CreateMap<ScheduledEventDTO, EventOccurrence>();
You can use ReverseMap() for create map to both direction. Investigate it.

2022-05-19 12:42 UTC, BobTheSuperman commented on scripts/1_generate_database.sql
> +	`Color`				INT 				NOT NULL,
I think better to use new script with alter table than  to initialize a new db with different data.

2022-05-23 13:33 UTC, BohdanZaliubovskyi commented on scripts/2_final_script_with_data.sql
> +(4, 4, 32, 5, 132,  '2021-11-19 10:00:00', '2021-11-19 11:00:00'),
Do we need this whitespace ?

2022-05-23 13:34 UTC, BohdanZaliubovskyi commented on scripts/2_final_script_with_data.sql
> +(5, 5, 38, 2, 164,  '2021-01-04 10:00:00', '2021-01-04 11:00:00'),
The same

2022-05-23 13:37 UTC, BohdanZaliubovskyi approved these changes

2022-05-24 00:54 UTC, BobTheSuperman approved these changes

2022-05-24 09:10 UTC, Ssashaa approved these changes

2022-05-26 12:28 UTC, apyura approved these changes

2022-05-26 12:28 UTC, apyura commented on CharlieBackend.Core/DTO/Schedule/UpdateScheduledEventDto.cs
> +
Please, remove newline

2022-05-26 12:28 UTC, apyura commented on CharlieBackend.Panel/CharlieBackend.Panel.csproj
> +    <Content Remove="wwwroot\css\colorPick.min.css" />
please, remove duplicate

2022-05-26 12:28 UTC, apyura commented on CharlieBackend.Panel/CharlieBackend.Panel.csproj
> +    <None Include="wwwroot\js\colorPick.min.js" />
please, remove duplicate

2022-05-26 12:28 UTC, apyura commented on CharlieBackend.Panel/Extensions/Extensions.cs
> +                client.BaseAddress = new Uri(configuration.GetSection("Urls:Api:Http").Value);
please, remove protocol changes

2022-05-26 12:28 UTC, apyura commented on CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
> +                    result += writer.ToString();
please, use StringBuilder class for string operations

2022-05-26 12:28 UTC, apyura commented on CharlieBackend.Panel/HtmlHelpers/CalendarHelper.cs
> +            return btnClass;
please, add empty line before return operator (according to coding conventions)

2022-05-26 12:28 UTC, BohdanZaliubovskyi approved these changes

2022-05-31 12:24 UTC, andy-dendy-repo approved these changes

2022-05-31 12:25 UTC, Ssashaa approved these changes

2022-05-31 12:45 UTC, PavelTsyposhchuk approved these changes

2022-06-01 09:01 UTC, merged