Tests/881, Add tests for secretary service
ita-social-projects/WhatBackend pull request #885
Opened 2022-05-17 11:38 UTC by BohdanZaliubovskyi

Added test coverage for class CharlieBackend.Business\Services\SecretaryService
Added ICloneable interface for classes: Account, Attachement, BaseEntity, Secretary, SecretaryDto, UpdateSecretaryDto

**Test coverage results:**
**Before:**
![image](https://user-images.githubusercontent.com/51024027/168801594-e2dd2fe6-decb-4f24-9bb7-7158fc4f8c1a.png)
![image](https://user-images.githubusercontent.com/51024027/168801650-5d39cf4a-0355-4db2-be1c-d730afb8682a.png)

**After:**
![image](https://user-images.githubusercontent.com/51024027/168801702-86603b41-5304-4c21-95a9-4887cca67e16.png)
![image](https://user-images.githubusercontent.com/51024027/168801777-21f6b551-d21e-4165-a083-0cb1ec70fa53.png)

2022-05-17 12:45 UTC, PavelTsyposhchuk requested changes

2022-05-17 12:45 UTC, PavelTsyposhchuk commented on CharlieBackend.Core/Entities/Account.cs
> +                { }
not used ex

2022-05-17 13:22 UTC, BohdanZaliubovskyi commented on CharlieBackend.Core/Entities/Account.cs
> +                { }
Ty, it's just testing code.

2022-05-17 20:17 UTC, PavelTsyposhchuk approved these changes

2022-05-24 00:50 UTC, BobTheSuperman approved these changes

2022-05-24 09:43 UTC, apyura approved these changes

2022-05-24 09:43 UTC, apyura commented on CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
> +        Mock<ISecretaryRepository> _secretaryRepositoryMock;
please, add access modifier

2022-05-24 11:32 UTC, BohdanZaliubovskyi commented on CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
> +        Mock<ISecretaryRepository> _secretaryRepositoryMock;
Done

2022-05-24 13:54 UTC, apyura requested changes

2022-05-24 13:54 UTC, apyura commented on CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
> +        }
please, add newline between methods

2022-05-24 13:54 UTC, apyura commented on CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
> +                .Throws(new Exception());
Bad practice: exceptions throwing of base type

2022-05-25 14:57 UTC, BohdanZaliubovskyi commented on CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
> +                .Throws(new Exception());
Ok.
In code we have next situation:
```C#
catch
{
    _unitOfWork.Rollback();

    return Result<SecretaryDto>.GetError(ErrorCode.InternalServerError,
          "Cannot update secretary.");
}
```
We don't have any exception object and any type of exception, so what type of exception should i throw ?

2022-05-25 14:58 UTC, BohdanZaliubovskyi commented on CharlieBackend.Api.UnitTes/SecretaryServiceTests.cs
> +        }
Done.

2022-05-31 12:19 UTC, Ssashaa approved these changes

2022-05-31 12:20 UTC, apyura approved these changes

2022-05-31 12:20 UTC, andy-dendy-repo approved these changes

2022-05-31 12:21 UTC, DevPew01 approved these changes

2022-05-31 13:23 UTC, merged