Async await code refactoring
ita-social-projects/WhatBackend pull request #889
Opened 2022-05-18 12:25 UTC by PavelTsyposhchuk

Refactoring async-awaits antipatterns and mistakes

2022-05-19 09:40 UTC, DevPew01 commented on CharlieBackend.Business/Services/StudentGroupService.cs
> +            var lessonsOfStudentGroup = await _unitOfWork.LessonRepository.GetAllLessonsForStudentGroup(StudentGroupId);
Maybe need Async here?

2022-05-19 09:51 UTC, DevPew01 commented on CharlieBackend.Panel/Controllers/HomeworksController.cs
>                  .Where(z => z.ThemeName == themeN).Where(d => d.MentorId == mentorId).ToList();
In my opinion, this multiple delegates call  Where(...).Where(...)... in linq-to-objects more slower then one condition with &&  operators.

2022-05-19 15:26 UTC, BobTheSuperman approved these changes

2022-05-19 15:31 UTC, Ssashaa approved these changes

2022-05-19 15:37 UTC, BohdanZaliubovskyi approved these changes
Look's good for me.

2022-05-20 11:41 UTC, andy-dendy-repo commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Csv/StudentsGroupCsvFileExport.cs
> +            await _memoryStream.WriteAsync(byteLine);
why don't you remove async and return _memoryStream.WriteAsync(byteLine); ?

2022-05-20 11:43 UTC, andy-dendy-repo commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookHtmlFileExport.cs
> +                await _memoryStream.WriteAsync(byteLine);
the same with async and return

2022-05-20 11:44 UTC, andy-dendy-repo commented on CharlieBackend.Business/Services/FileServices/ExportFileServices/Html/ClassbookHtmlFileExport.cs
> +                await _memoryStream.WriteAsync(byteLine);
the same

2022-05-23 07:19 UTC, DevPew01 approved these changes

2022-06-12 18:29 UTC, fllimon requested changes
Looks good

2022-06-12 18:29 UTC, fllimon approved these changes

2022-06-12 19:58 UTC, merged